{% set python_min = "3.10" %}
{% set name = "hats-import" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hats-import/archive/v{{ version }}.tar.gz
  sha256: 65f8bbec5d4c4b5fd0c46aca2bbc8642d39779b7dcb8ceb5de9af8abfd62a0bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - dask-core >=2024.3.0
    - distributed >=2024.3.0
    - deprecated
    - hats >=0.4.5
    - ipykernel
    - numpy
    - pandas
    - pyarrow
    - pyyaml
    - tqdm
    - universal_pathlib

test:
  imports:
    - hats_import
  commands:
    - pip check
    - pytest tests --timeout=0
  requires:
    - pip
    - pytest
    - pytest-timeout
    - ray-core
    - python {{ python_min }}
  source_files:
    - tests
    - pyproject.toml

about:
  home: https://github.com/astronomy-commons/hats-import
  summary: 'A HATS astronomical catalog import tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
