{% set python_min = "3.10" %}
{% set name = "hats-import" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hats-import/archive/v{{ version }}.tar.gz
  sha256: 6dd75b40877bb35dcdd83e880759ee7cd62da0d966bfae10feb2fda802f40970

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - dask-core >=2024.3.0,<2025.4.0
    - distributed >=2024.3.0,<2025.4.0
    - deprecated
    - hats >=0.6.6,<0.7.0
    - ipykernel
    - numpy
    - pandas
    - pyarrow
    - pyyaml
    - tqdm
    - universal_pathlib >=0.2.2,<0.3.0

test:
  imports:
    - hats_import
  commands:
    - pip check
    - pytest tests --timeout=0
  requires:
    - pip
    - pytest
    - pytest-timeout
    - pytest-mock
    - python {{ python_min }}
  source_files:
    - tests
    - pyproject.toml

about:
  home: https://github.com/astronomy-commons/hats-import
  summary: 'A HATS astronomical catalog import tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
