{% set python_min = "3.10" %}
{% set name = "hats-import" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hats-import/archive/v{{ version }}.tar.gz
  sha256: 0825538960f26f2f9db3895a77427aa6daf81d713824b325121ca9a2e818b594

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - dask-core >=2024.3.0
    - distributed >=2024.3.0
    - deprecated
    - hats >=0.4.6
    - ipykernel
    - numpy
    - pandas
    - pyarrow
    - pyyaml
    - tqdm
    - universal_pathlib

test:
  imports:
    - hats_import
  commands:
    - pip check
    - pytest tests --timeout=0
  requires:
    - pip
    - pytest
    - pytest-timeout
    - ray-core
    - python {{ python_min }}
  source_files:
    - tests
    - pyproject.toml

about:
  home: https://github.com/astronomy-commons/hats-import
  summary: 'A HATS astronomical catalog import tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
