{% set name = "hats-import" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hats-import/archive/v{{ version }}.tar.gz
  sha256: 0f1b52a1f7859788d70b5dc2021cc013df5fa9e0df4fe7a53c462b9d2c66040a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.10
    - dask-core >=2024.3.0
    - distributed >=2024.3.0
    - deprecated
    - hats >=0.4.5
    - ipykernel
    - numpy
    - pandas
    - pyarrow
    - pyyaml
    - tqdm
    - universal_pathlib

test:
  imports:
    - hats_import
  commands:
    - pip check
    - pytest tests --timeout=0
  requires:
    - pip
    - pytest
    - pytest-timeout
    - ray-core
  source_files:
    - tests
    - pyproject.toml

about:
  home: https://github.com/astronomy-commons/hats-import
  summary: 'A HATS astronomical catalog import tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
