{% set python_min = "3.10" %}
{% set name = "hats-import" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hats-import/archive/v{{ version }}.tar.gz
  sha256: bea9e3cd8c5fa7f37bfaf3745e5b9369f89ae57f214572b515bb0d2823272c1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - cloudpickle >=3.0.0
    - dask-core >=2024.3.0,<2025.4.0
    - deprecated
    - distributed
    - hats >=0.7.3,<0.8
    - ipykernel
    - nested-pandas >=0.6.3,<0.7.0
    - numpy >=2.2.0,<3
    - pandas >=2.0
    - tqdm >=4.59.0
    - universal_pathlib

test:
  imports:
    - hats_import
  commands:
    - pip check
    - pytest tests --timeout=0
  requires:
    - pip
    - pytest
    - pytest-timeout
    - pytest-mock
    - python {{ python_min }}
  source_files:
    - tests
    - pyproject.toml

about:
  home: https://github.com/astronomy-commons/hats-import
  summary: 'A HATS astronomical catalog import tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smcguire-cmu
    - olivialynn
    - gitosaurus
    - dougbrn
    - hombit
    - astronomy-commons/lincc-frameworks
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
